### ISSUE TITLE
How to switch layers with default layout

### ISSUE THREAD

**Issue by awdsmirk** [Lectral13/KC60#2]
Hello,
On the Massdrop discussion for the KC60, there's a comment from a user that states the following:
"left shift + right shift + 0, for first layer, 1 for second layer, 2 for third layer. "
This information is useful for newbies like me that want to keep the default layout and not mess around with flashing.  Hitting the above key combos will cycle through the 3 default layers which are described here: http://123.57.250.164:9128/
Hope it helps others.
Credit to user below in screenshot:
<img width="1440" alt="screen shot 2015-10-28 at 8 57 56 pm" src="https://cloud.githubusercontent.com/assets/1934605/10809765/e543b902-7db6-11e5-94d3-189d949bdd55.png">

**Comment by Lectral13** [comment]
thank you awdsmirk for pointing that out, I had missed that.  It should work even after you program the board up to all 9 layers.
